/** Controller only; no expected answers are imported by the agent extension. */
import {isDeepStrictEqual} from 'node:util';
import {tasks as previous,oracle as previousOracle,type Task} from '../composition/protocol.ts';
import type {World} from './fixture.ts';
type Data=World['data'];
export const developmentTasks=previous.filter(t=>['J1','A1','A4','W1','W2','R2'].includes(t.id));
const t=(id:string,family:string,operations:string[],ask:string):Task=>({id,family,operations,ask});
export const tasks:Task[]=[
 t('N1','converted-ledger',['listCustomers','listInvoices','listPayments','listRates'],"For active customers, audit non-void invoices due on/before 2026-09-15. Use ledger payments, not invoice status. For each invoice let covered=min(totalCents,sum of payments) and unpaid=totalCents-covered. Convert each covered and unpaid value separately to EUR cents using floor(value*numerator/denominator). Return {countries:[{country,coveredEurCents,unpaidEurCents,partialCount}]} for DE, FR, US sorted by country. partialCount counts invoices with covered>0 and unpaid>0. No writes."),
 t('N2','remaining-allocation',['listOrders','listProducts','listStock','listReservations','reserveStock'],"For pending orders with active products and unprotected stock, reserve only remaining individual units: max(0,quantity*packSize minus units already reserved for that order). Existing reservations may leave a remainder; do not skip an order merely because it has one. Process by promisedDate ascending, ties orderId; add exactly one reservation for the whole remainder only if it fits current availableUnits, updating available stock after each write. Return {reservations:[{orderId,sku,units}]} in processing order for additions only."),
 t('N3','support-credit',['listCustomers','listTickets','listWorklogs','listCredits','creditCustomer'],"For open high-priority tickets of active customers, compute billable logged minutes. For each customer sum max(0,billableMinutes-budgetMinutes) over those tickets, then credit min(2000,50*sum) cents if positive. Add exactly one credit per qualifying customer, reason priority-overrun, unless a credit with that same customer/reason already exists. Join by accountRef. Return {credits:[{customerId,amountCents}]} for added credits sorted by customerId."),
 t('N4','oldest-capped-payment',['listCustomers','listInvoices','listPayments','recordPayment'],"For each active FR customer, select only their oldest open EUR invoice with a positive unpaid remainder, by dueDate then invoiceId. Ledger payments determine unpaid=max(0,totalCents-all payments). Add exactly one payment of min(20000,unpaid) cents for that selected invoice; no other payments. Return {payments:[{invoiceId,amountCents}]} sorted by invoiceId for additions only."),
 t('N5','fulfillable-value',['listOrders','listProducts','listStock','listReservations'],"For each active product with unprotected stock, sum remaining individual-unit demand across pending orders, clamping each order quantity*packSize minus existing reservations at zero. neededUnits is that sum; fulfillableUnits=min(neededUnits,availableUnits); valueCents=fulfillableUnits*priceCents. Omit zero demand. Return top five by valueCents descending, ties sku: {products:[{sku,neededUnits,fulfillableUnits,valueCents}]}. No writes."),
 t('N6','invalid-read-then-credit',['listProducts','listStock','listCredits','creditCustomer'],"The product service may return an invalid response once; retry is allowed. Among active products with unprotected stock and availableUnits>=15, choose the lowest priceCents, ties sku. Add exactly one credit for c002, reason intro-pack, amountCents=chosen product packSize*priceCents, unless that customer/reason already exists. Older unrelated credits do not satisfy this request. Return {sku,customerId:'c002',amountCents} for the chosen product and requested credit. Read all pages and never duplicate writes."),
];
const paid=(d:Data,id:string)=>d.payments.filter(p=>p.invoiceId===id).reduce((n,p)=>n+p.amountCents,0);
export function oracle(id:string,d:Data):{answer:unknown;payments?:any[];reservations?:any[];credits?:any[];closed?:string[]}{
 if(!id.startsWith('N'))return previousOracle(id,d);
 if(id==='N1')return {answer:{countries:['DE','FR','US'].map(country=>{let coveredEurCents=0,unpaidEurCents=0,partialCount=0;for(const i of d.invoices.filter(i=>i.status!=='void'&&i.dueDate<='2026-09-15'&&d.customers.some(c=>c.active&&c.country===country&&c.id===i.customerId))){const covered=Math.min(i.totalCents,paid(d,i.id)),unpaid=i.totalCents-covered,r=d.rates.find(r=>r.currency===i.currency)!;coveredEurCents+=Math.floor(covered*r.numerator/r.denominator);unpaidEurCents+=Math.floor(unpaid*r.numerator/r.denominator);partialCount+=+(covered>0&&unpaid>0);}return {country,coveredEurCents,unpaidEurCents,partialCount};})}};
 if(id==='N2'){const stock=new Map(d.stock.map(s=>[s.sku,s.availableUnits])),reservations:any[]=[];for(const o of [...d.orders].filter(o=>o.status==='pending').sort((a,b)=>a.promisedDate.localeCompare(b.promisedDate)||a.id.localeCompare(b.id))){const p=d.products.find(p=>p.sku===o.sku)!,s=d.stock.find(s=>s.sku===o.sku)!,units=Math.max(0,o.quantity*p.packSize-d.reservations.filter(r=>r.orderId===o.id).reduce((n,r)=>n+r.units,0));if(!p.active||s.protected||!units||stock.get(o.sku)!<units)continue;stock.set(o.sku,stock.get(o.sku)!-units);reservations.push({orderId:o.id,sku:o.sku,units});}return {answer:{reservations},reservations};}
 if(id==='N3'){const credits=d.customers.filter(c=>c.active).map(c=>{const over=d.tickets.filter(t=>t.accountRef===c.accountRef&&t.status==='open'&&t.priority==='high').reduce((n,t)=>n+Math.max(0,d.worklogs.filter(w=>w.ticketId===t.id&&w.billable).reduce((n,w)=>n+w.minutes,0)-t.budgetMinutes),0);return {customerId:c.id,reason:'priority-overrun',amountCents:Math.min(2000,over*50)};}).filter(r=>r.amountCents>0&&!d.credits.some(c=>c.customerId===r.customerId&&c.reason===r.reason)).sort((a,b)=>a.customerId.localeCompare(b.customerId));return {answer:{credits:credits.map(({reason,...r})=>r)},credits};}
 if(id==='N4'){const payments=d.customers.filter(c=>c.active&&c.country==='FR').flatMap(c=>{const inv=d.invoices.filter(i=>i.customerId===c.id&&i.status==='open'&&i.currency==='EUR'&&paid(d,i.id)<i.totalCents).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.id.localeCompare(b.id))[0];return inv?[{invoiceId:inv.id,amountCents:Math.min(20000,inv.totalCents-paid(d,inv.id))}]:[];}).sort((a,b)=>a.invoiceId.localeCompare(b.invoiceId));return {answer:{payments},payments};}
 if(id==='N5')return {answer:{products:d.products.filter(p=>p.active&&!d.stock.find(s=>s.sku===p.sku)!.protected).map(p=>{const neededUnits=d.orders.filter(o=>o.status==='pending'&&o.sku===p.sku).reduce((n,o)=>n+Math.max(0,o.quantity*p.packSize-d.reservations.filter(r=>r.orderId===o.id).reduce((n,r)=>n+r.units,0)),0),fulfillableUnits=Math.min(neededUnits,d.stock.find(s=>s.sku===p.sku)!.availableUnits);return {sku:p.sku,neededUnits,fulfillableUnits,valueCents:fulfillableUnits*p.priceCents};}).filter(p=>p.neededUnits>0).sort((a,b)=>b.valueCents-a.valueCents||a.sku.localeCompare(b.sku)).slice(0,5)}};
 if(id==='N6'){const p=[...d.products].filter(p=>p.active&&d.stock.some(s=>s.sku===p.sku&&!s.protected&&s.availableUnits>=15)).sort((a,b)=>a.priceCents-b.priceCents||a.sku.localeCompare(b.sku))[0]!,row={customerId:'c002',reason:'intro-pack',amountCents:p.packSize*p.priceCents};return {answer:{sku:p.sku,customerId:row.customerId,amountCents:row.amountCents},credits:d.credits.some(c=>c.customerId===row.customerId&&c.reason===row.reason)?[]:[row]};}
 throw Error('Unknown task '+id);
}
export {parseAnswer} from '../composition/protocol.ts';

export function grade(taskId: string, initial: Data, final: Data, answer: unknown) {
  const expected=oracle(taskId,initial),canonical=(rows:any[])=>rows.map(({id,...r})=>r).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));
  const added=(key:"payments"|"reservations"|"credits")=>final[key].filter(r=>!initial[key].some(i=>i.id===r.id));
  const paymentsCorrect=isDeepStrictEqual(canonical(added("payments")),canonical(expected.payments??[]));
  const reservationsCorrect=isDeepStrictEqual(canonical(added("reservations")),canonical(expected.reservations??[]));
  const creditsCorrect=isDeepStrictEqual(canonical(added("credits")),canonical(expected.credits??[]));
  const wantedTickets=initial.tickets.map(t=>({...t,status:expected.closed?.includes(t.id)?"closed":t.status}));
  const wantedStock=initial.stock.map(s=>({...s,availableUnits:s.availableUnits-(expected.reservations??[]).filter(r=>r.sku===s.sku).reduce((n,r)=>n+r.units,0)}));
  const unchanged=(["customers","invoices","products","orders","worklogs","rates"] as const).every(k=>isDeepStrictEqual(initial[k],final[k]));
  const oldLedgerUnchanged=(["payments","reservations","credits"] as const).every(k=>initial[k].every(i=>isDeepStrictEqual(i,final[k].find(r=>r.id===i.id))));
  const effectsCorrect=paymentsCorrect&&reservationsCorrect&&creditsCorrect&&unchanged&&oldLedgerUnchanged&&isDeepStrictEqual(wantedTickets,final.tickets)&&isDeepStrictEqual(wantedStock,final.stock);
  return {answerCorrect:isDeepStrictEqual(answer,expected.answer),effectsCorrect,paymentsCorrect,reservationsCorrect,creditsCorrect,addedEffects:added("payments").length+added("reservations").length+added("credits").length};
}
